export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const RESIZE_MODAL = "RESIZE_MODAL";
export const TOGGLE_RESIZE_MODAL = "TOGGLE_RESIZE_MODAL";
export const TOGGLE_DRAGGABLE_MODAL = "TOGGLE_DRAGGABLE_MODAL";
export const MOVE_MODAL = "MOVE_MODAL";
export const SET_ACTIVE_MODAL = "SET_ACTIVE_MODAL";
export const CLOSE_ALL_MODALS = "CLOSE_ALL_MODALS";

